server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/claim_center
    username: claimcenter
    password: claimcenter
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

