server:
  port: 8082
spring:
  application:
    name: tenant-service
  datasource:
    url: jdbc:postgresql://postgres:5432/claim_center
    username: claimcenter
    password: claimcenter
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
