apiVersion: v1
kind: ConfigMap
metadata:
  name: claim-center-config
  namespace: claim-center
data:
  JWT_SECRET: 0123456789abcdef0123456789abcdef
  DB_URL: jdbc:postgresql://postgres:5432/claim_center
