apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claim-center
  namespace: claim-center
spec:
  rules:
    - host: claim-center.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
